### ISSUE TITLE
Improve test run output

### ISSUE THREAD

**Issue by pihme** [zeebe-io/bpmn-spec#30]
**Is your feature request related to a problem? Please describe.**
If tests are run as part of the Jenkins pipeline, the JUnit5 test names are not carried over.

See e.g.: https://ci.zeebe.camunda.cloud/job/zeebe-io/job/zeebe/job/5595-add-tck-tests/11/testReport/io.zeebe.bpmn.tck/BpmnTest/

**Describe the solution you'd like**
* Find a way to get the names into the JUnit test report files
* Alternatively, add output for the tests so that a developer can read which test was ran.

**Comment by saig0** [comment]
I think this is not a concrete problem for this project. It seems to be related to https://github.com/junit-team/junit5/issues/990 / https://issues.apache.org/jira/browse/SUREFIRE-1546.

You may need to configure the surefire plugin to show the display names. See https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html.
